exclude:
  - lib/templates/haml/scaffold/_form.html.haml

linters:
  LineLength:
    max: 120

  InstanceVariables:
    enabled: false

  InlineStyles:
    enabled: false

  IdNames:
    enabled: false
