AllCops:
  TargetRubyVersion: 3.3.8
  NewCops: enable
  Exclude:
    - bin/*
    - config/boot.rb
    - config/initializers/*
    - config/environments/*
    - db/migrate/*
    - db/schema.rb

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'config/routes.rb'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 1500

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 1500

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/DuplicateBranch:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%w': '()'
    '%W': '()'
    '%i': '()'
    '%I': '()'

Style/RedundantReturn:
  Enabled: false

Style/StringConcatenation:
  Enabled: false # as we have many right-to-left texts following this Cop can be tricky

# TODO: Re-enable later, currently too hard to fix all places
Style/UnlessElse:
  Enabled: false

Rails/ActionOrder: # TODO: temporary disabled. it would be good to enable in future
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/OutputSafety: # we actively use such output
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

FactoryBot/ExcessiveCreateList:
  MaxAmount: 100

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false
