volumes:
  mysql_data:
  bundler_data:
  elasticsearch_data:
services:
  mysql:
    image: mysql:8.0.36
    restart: unless-stopped
    command: --max_allowed_packet=256M      # Set max_allowed_packet to 256M (or any other value)
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
    volumes:
      - mysql_data:/var/lib/mysql/:delegated
  elasticsearch:
    image: elasticsearch:7.17.8
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
      - action.destructive_requires_name=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:delegated
    ports:
      - 19200:9200
      - 19300:9300
  kibana:
    image: kibana:7.17.8
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 15601:5601
    depends_on:
      - elasticsearch
  memcached:
    image: memcached:1.6.17
    restart: unless-stopped
  redis:
    image: redis:7.2.3
    restart: unless-stopped
    ports:
      - 16379:6379
  test-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    command: rspec
    environment:
      - RAILS_ENV=test
    volumes:
      - ./.git:/app/.git
      - ./.gitignore:/app/.gitignore
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./config/constants.yml.sample:/app/config/constants.yml
      - ./config/s3.yml.sample:/app/config/s3.yml
      - ./config/storage.yml.sample:/app/config/storage.yml
      - ./db:/app/db
      - ./js:/app/js
      - ./lib:/app/lib
      - ./spec:/app/spec
      - ./vendor:/app/vendor
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./Rakefile:/app/Rakefile
      - ./config.ru:/app/config.ru
      - ./docker/.env.test-app:/app/.env
      - ./docker/test-app.sh:/app/test-app.sh
      - bundler_data:/usr/local/bundle/:delegated
    depends_on:
      - mysql
      - redis
      - elasticsearch
    restart: no