volumes:
  mysql_data:
  elasticsearch_data:
services:
  mysql:
    image: mysql:8.0.36
    restart: unless-stopped
    command: --max_allowed_packet=256M      # Set max_allowed_packet to 256M (or any other value)
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
    volumes:
      - mysql_data:/var/lib/mysql/:delegated
  elasticsearch:
    image: elasticsearch:7.17.8
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
      - action.destructive_requires_name=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:delegated
    ports:
      - 19200:9200
      - 19300:9300
  kibana:
    image: kibana:7.17.8
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 15601:5601
    depends_on:
      - elasticsearch
  memcached:
    image: memcached:1.6.17
    restart: unless-stopped
  redis:
    image: redis:7.2.3
    restart: unless-stopped
    ports:
      - 16379:6379
