version: '3'

volumes:
  mysql_data:
  bundler_data:
  elasticsearch_data:
services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    command: --max_allowed_packet=256M      # Set max_allowed_packet to 256M (or any other value)
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql/:delegated
  elasticsearch:
    image: elasticsearch:6.8.23
    restart: unless-stopped
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:delegated
    ports:
      - 9201:9200
      - 9301:9300
  kibana:
    image: kibana:6.8.23
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5602:5601
    depends_on:
      - elasticsearch
  memcached:
    image: memcached:1.6.17
    restart: unless-stopped
  app:
    build: ..
    environment:
      - MEMCACHE_SERVERS=http://memcached:11211
    ports:
      - 3001:3000
    volumes:
      - ../..:/app
      - bundler_data:/usr/local/bundle/:delegated
    depends_on:
      - mysql
      - memcached
      - elasticsearch
