# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/collections' do
  # Collection. As you add validations to Collection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Collection.create! valid_attributes
      get collections_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      collection = Collection.create! valid_attributes
      get collection_url(collection)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      fake_editor(CollectionsController)
      get new_collection_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      collection = Collection.create! valid_attributes
      get edit_collection_url(collection)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Collection' do
        expect do
          post collections_url, params: { collection: valid_attributes }
        end.to change(Collection, :count).by(1)
      end

      it 'redirects to the created collection' do
        post collections_url, params: { collection: valid_attributes }
        expect(response).to redirect_to(collection_url(Collection.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Collection' do
        expect do
          post collections_url, params: { collection: invalid_attributes }
        end.not_to change(Collection, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post collections_url, params: { collection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested collection' do
        collection = Collection.create! valid_attributes
        patch collection_url(collection), params: { collection: new_attributes }
        collection.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the collection' do
        collection = Collection.create! valid_attributes
        patch collection_url(collection), params: { collection: new_attributes }
        collection.reload
        expect(response).to redirect_to(collection_url(collection))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        collection = Collection.create! valid_attributes
        patch collection_url(collection), params: { collection: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested collection' do
      collection = Collection.create! valid_attributes
      expect do
        delete collection_url(collection)
      end.to change(Collection, :count).by(-1)
    end

    it 'redirects to the collections list' do
      collection = Collection.create! valid_attributes
      delete collection_url(collection)
      expect(response).to redirect_to(collections_url)
    end
  end
end
