require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/corporate_bodies", type: :request do
  
  # CorporateBody. As you add validations to CorporateBody, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CorporateBody.create! valid_attributes
      get corporate_bodies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      corporate_body = CorporateBody.create! valid_attributes
      get corporate_body_url(corporate_body)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_corporate_body_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      corporate_body = CorporateBody.create! valid_attributes
      get edit_corporate_body_url(corporate_body)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CorporateBody" do
        expect {
          post corporate_bodies_url, params: { corporate_body: valid_attributes }
        }.to change(CorporateBody, :count).by(1)
      end

      it "redirects to the created corporate_body" do
        post corporate_bodies_url, params: { corporate_body: valid_attributes }
        expect(response).to redirect_to(corporate_body_url(CorporateBody.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CorporateBody" do
        expect {
          post corporate_bodies_url, params: { corporate_body: invalid_attributes }
        }.to change(CorporateBody, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post corporate_bodies_url, params: { corporate_body: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested corporate_body" do
        corporate_body = CorporateBody.create! valid_attributes
        patch corporate_body_url(corporate_body), params: { corporate_body: new_attributes }
        corporate_body.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the corporate_body" do
        corporate_body = CorporateBody.create! valid_attributes
        patch corporate_body_url(corporate_body), params: { corporate_body: new_attributes }
        corporate_body.reload
        expect(response).to redirect_to(corporate_body_url(corporate_body))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        corporate_body = CorporateBody.create! valid_attributes
        patch corporate_body_url(corporate_body), params: { corporate_body: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested corporate_body" do
      corporate_body = CorporateBody.create! valid_attributes
      expect {
        delete corporate_body_url(corporate_body)
      }.to change(CorporateBody, :count).by(-1)
    end

    it "redirects to the corporate_bodies list" do
      corporate_body = CorporateBody.create! valid_attributes
      delete corporate_body_url(corporate_body)
      expect(response).to redirect_to(corporate_bodies_url)
    end
  end
end
