 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lex_people", type: :request do
  
  # LexPerson. As you add validations to LexPerson, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LexPerson.create! valid_attributes
      get lex_people_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lex_person = LexPerson.create! valid_attributes
      get lex_person_url(lex_person)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lex_person_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      lex_person = LexPerson.create! valid_attributes
      get edit_lex_person_url(lex_person)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LexPerson" do
        expect {
          post lex_people_url, params: { lex_person: valid_attributes }
        }.to change(LexPerson, :count).by(1)
      end

      it "redirects to the created lex_person" do
        post lex_people_url, params: { lex_person: valid_attributes }
        expect(response).to redirect_to(lex_person_url(LexPerson.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LexPerson" do
        expect {
          post lex_people_url, params: { lex_person: invalid_attributes }
        }.to change(LexPerson, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post lex_people_url, params: { lex_person: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lex_person" do
        lex_person = LexPerson.create! valid_attributes
        patch lex_person_url(lex_person), params: { lex_person: new_attributes }
        lex_person.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lex_person" do
        lex_person = LexPerson.create! valid_attributes
        patch lex_person_url(lex_person), params: { lex_person: new_attributes }
        lex_person.reload
        expect(response).to redirect_to(lex_person_url(lex_person))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        lex_person = LexPerson.create! valid_attributes
        patch lex_person_url(lex_person), params: { lex_person: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lex_person" do
      lex_person = LexPerson.create! valid_attributes
      expect {
        delete lex_person_url(lex_person)
      }.to change(LexPerson, :count).by(-1)
    end

    it "redirects to the lex_people list" do
      lex_person = LexPerson.create! valid_attributes
      delete lex_person_url(lex_person)
      expect(response).to redirect_to(lex_people_url)
    end
  end
end
