 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lex_links", type: :request do
  
  # LexLink. As you add validations to LexLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LexLink.create! valid_attributes
      get lex_links_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lex_link = LexLink.create! valid_attributes
      get lex_link_url(lex_link)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_lex_link_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      lex_link = LexLink.create! valid_attributes
      get edit_lex_link_url(lex_link)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LexLink" do
        expect {
          post lex_links_url, params: { lex_link: valid_attributes }
        }.to change(LexLink, :count).by(1)
      end

      it "redirects to the created lex_link" do
        post lex_links_url, params: { lex_link: valid_attributes }
        expect(response).to redirect_to(lex_link_url(LexLink.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LexLink" do
        expect {
          post lex_links_url, params: { lex_link: invalid_attributes }
        }.to change(LexLink, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post lex_links_url, params: { lex_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lex_link" do
        lex_link = LexLink.create! valid_attributes
        patch lex_link_url(lex_link), params: { lex_link: new_attributes }
        lex_link.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lex_link" do
        lex_link = LexLink.create! valid_attributes
        patch lex_link_url(lex_link), params: { lex_link: new_attributes }
        lex_link.reload
        expect(response).to redirect_to(lex_link_url(lex_link))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        lex_link = LexLink.create! valid_attributes
        patch lex_link_url(lex_link), params: { lex_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lex_link" do
      lex_link = LexLink.create! valid_attributes
      expect {
        delete lex_link_url(lex_link)
      }.to change(LexLink, :count).by(-1)
    end

    it "redirects to the lex_links list" do
      lex_link = LexLink.create! valid_attributes
      delete lex_link_url(lex_link)
      expect(response).to redirect_to(lex_links_url)
    end
  end
end
