openapi: 3.1.0
info:
  title: Project Ben-Yehuda API
  version: 1.0.0
components:
  schemas:
    genre:
      type: string
      enum: ["poetry", "prose", "drama", "fables","article", "memoir", "letters", "reference", "lexicon"]
      description: "the broad field of humanities of a textual work in the database."
    period:
      type: string
      enum: ["ancient", "medieval", "enlightenment", "revival", "modern"]
      description: "specifies what section of the rough timeline of Hebrew literature an object belongs to."
paths: 
  /text{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      summary: "returns meta-data and, optionally, the full text, of a textual work from the database"
      description: "(TBD)"
  parameters:
  - name: key
    in: query
    required: true
    schema:
      type: string
servers:
  - url: "https://benyehuda.org/api"
    description: "main production server of Project Ben-Yehuda"