# All connection settings like host, port, db_name and credentials to be defined in
# DATABASE_URL environment variable (Rails uses it by default)
# This file is only used for passing additional options to db adapter

default: &default
  encoding: utf8mb4
  collation: utf8mb4_bin

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
