FROM cimg/ruby:2.6.8

RUN sudo apt update
RUN sudo apt install -y libsqlite3-dev wkhtmltopdf pandoc yaz libyaz-dev  libmagickwand-dev libpcap-dev memcached
RUN sudo apt clean

LABEL maintainer="Damir Sultanbekov <damir.sultanbekov@gmail.com>"
